version: "3"

services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
    restart: always
    shm_size: 2g
  server:
    build:
      context: .
    depends_on:
      - selenium
    volumes:
      - ./app:/app
    command: sh -c "python3 bot.py"
